spring.application.name=x6-user

server.port = 8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://192.168.88.205:5432/x6user
spring.datasource.username=javajabka
spring.datasource.password=${DB_PG_PWD}

spring.data.redis.host=192.168.88.12
spring.data.redis.port=6379
spring.cache.type=redis

springdoc.swagger-ui.path=/swagger-ui

logging.file.name=x6user_errors.log